### ISSUE TITLE
Automatically include the binary applications on Release action

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/antares-launcher#50]
As a developer, I want to automatically include the binary applications generated during a push to the `main` (or `support`) branch in the assets of a GitHub release, so that users can easily download and use the latest version of the applications.

Currently, the binary applications are generated with the [`.github/workflows/binary.yml`](https://github.com/AntaresSimulatorTeam/antares-launcher/blob/93468569e11f06e56d0081e7812a3f61ef4d7558/.github/workflows/binary.yml) workflow. Two artifacts are generated: one for Windows and the other for Ubuntu.

We want to create a new workflow, named for instance `release-assets.yml`, to publish the artifacts generated by `binary.yml`. So, we can use [`.github/workflows/python-publish.yml`](https://github.com/AntaresSimulatorTeam/antares-launcher/blob/93468569e11f06e56d0081e7812a3f61ef4d7558/.github/workflows/python-publish.yml) as an example. This workflow is only triggered when a Release is manually done on GitHub.

The following job is an **example** that downloads the binary artifacts from the `binary.yml` job and adds them to the release as assets.

```yaml
  release:
    needs: binary
    runs-on: ubuntu-latest
    steps:
      - name: Download binary artifacts
        uses: actions/download-artifact@v2
        with:
          name: binary-artifacts
          path: binaries

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Add release notes here

      - name: Upload release assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: binaries/
          asset_name: binaries.zip
          asset_content_type: application/zip
```

Update the `binary.yml` workflow to use the same artifact name as the `upload-artifact` action above.
